// Generated by scripts/generate-brand.mjs. Do not hand-edit.
// Canonical Core Graphics renderer for the portable DictaDuo icon model.
// scripts/generate-brand.mjs includes this source in the app and CLI exports.
import Foundation
import CoreGraphics

enum BrandIconRenderer {
    struct Model: Codable, Sendable {
        let canvas: Double
        let paths: [String: [Command]]
        let paints: [String: Paint]
        let layers: [Layer]
    }

    struct Command: Codable, Sendable {
        let op: String
        let values: [Double]
    }

    struct Paint: Codable, Sendable {
        let kind: String
        let color: String?
        let opacity: Double?
        let from: [Double]?
        let to: [Double]?
        let center: [Double]?
        let radius: Double?
        let stops: [Stop]?
    }

    struct Stop: Codable, Sendable {
        let offset: Double
        let color: String
        let opacity: Double?
    }

    struct Layer: Codable, Sendable {
        let path: String
        let paint: String
        let mode: String
        let width: Double?
        let offset: [Double]?
        let clip: String?
    }

    enum RenderError: Error, CustomStringConvertible {
        case invalid(String)

        var description: String {
            switch self {
            case .invalid(let reason): "Invalid DictaDuo icon model: \(reason)"
            }
        }
    }

    private enum LayerMode: String {
        case fill, stroke, fillStroke
    }

    private enum PreparedPaint {
        case solid(CGColor)
        case linear(CGGradient, CGPoint, CGPoint)
        case radial(CGGradient, CGPoint, CGFloat)

        func draw(in context: CGContext) {
            switch self {
            case .solid(let color):
                context.setFillColor(color)
                context.fill(context.boundingBoxOfClipPath)
            case .linear(let gradient, let from, let to):
                context.drawLinearGradient(gradient, start: from, end: to,
                                           options: [.drawsBeforeStartLocation, .drawsAfterEndLocation])
            case .radial(let gradient, let center, let radius):
                context.drawRadialGradient(gradient, startCenter: center, startRadius: 0,
                                           endCenter: center, endRadius: radius,
                                           options: [.drawsBeforeStartLocation, .drawsAfterEndLocation])
            }
        }
    }

    private struct PreparedLayer {
        let path: CGPath
        let paint: PreparedPaint
        let mode: LayerMode
        let width: CGFloat
        let offset: CGPoint
        let clip: CGPath?
    }

    /// The caller supplies a y-down context. A square canvas is fitted uniformly
    /// and centered in rect. Layer offsets move geometry, paint, and its clip
    /// together. Paint coordinates are absolute canvas coordinates, not bounds.
    static func draw(_ model: Model, in rect: CGRect, context: CGContext) throws {
        guard model.canvas.isFinite, model.canvas > 0 else {
            throw RenderError.invalid("canvas must be a finite positive number")
        }
        guard [rect.minX, rect.minY, rect.width, rect.height].allSatisfy({ $0.isFinite }),
              rect.width > 0, rect.height > 0 else {
            throw RenderError.invalid("destination rectangle must be finite and nonempty")
        }
        guard !model.paths.isEmpty, !model.paints.isEmpty, !model.layers.isEmpty else {
            throw RenderError.invalid("paths, paints, and layers must be present")
        }
        guard let colorSpace = CGColorSpace(name: CGColorSpace.sRGB) else {
            throw RenderError.invalid("sRGB color space is unavailable")
        }

        // Preflight every resource and reference before changing the destination.
        var paths: [String: CGPath] = [:]
        for (name, commands) in model.paths {
            paths[name] = try makePath(commands, named: name)
        }
        var paints: [String: PreparedPaint] = [:]
        for (name, paint) in model.paints {
            paints[name] = try prepare(paint, named: name, colorSpace: colorSpace)
        }
        let layers = try model.layers.enumerated().map { index, layer -> PreparedLayer in
            guard let path = paths[layer.path] else {
                throw RenderError.invalid("layer \(index) refers to unknown path \(layer.path)")
            }
            guard let paint = paints[layer.paint] else {
                throw RenderError.invalid("layer \(index) refers to unknown paint \(layer.paint)")
            }
            guard let mode = LayerMode(rawValue: layer.mode) else {
                throw RenderError.invalid("layer \(index) has unsupported mode \(layer.mode)")
            }
            let width = layer.width ?? 1
            guard width.isFinite, width > 0 else {
                throw RenderError.invalid("layer \(index) stroke width must be finite and positive")
            }
            let offset = try point(layer.offset ?? [0, 0], named: "layer \(index) offset")
            let clip: CGPath?
            if let name = layer.clip {
                guard let clipPath = paths[name] else {
                    throw RenderError.invalid("layer \(index) refers to unknown clip \(name)")
                }
                clip = clipPath
            } else {
                clip = nil
            }
            return PreparedLayer(path: path, paint: paint, mode: mode,
                                 width: CGFloat(width), offset: offset, clip: clip)
        }
        let scale = min(rect.width, rect.height) / CGFloat(model.canvas)
        let origin = CGPoint(x: rect.minX + (rect.width - CGFloat(model.canvas) * scale) / 2,
                             y: rect.minY + (rect.height - CGFloat(model.canvas) * scale) / 2)
        guard scale.isFinite, scale > 0, origin.x.isFinite, origin.y.isFinite else {
            throw RenderError.invalid("destination scale is invalid")
        }

        context.saveGState()
        defer { context.restoreGState() }
        context.clip(to: rect)
        context.translateBy(x: origin.x, y: origin.y)
        context.scaleBy(x: scale, y: scale)
        context.clip(to: CGRect(x: 0, y: 0, width: CGFloat(model.canvas), height: CGFloat(model.canvas)))
        context.setShouldAntialias(true)
        context.setBlendMode(.normal)
        context.setAlpha(1)
        context.setShadow(offset: .zero, blur: 0, color: nil)
        for layer in layers { draw(layer, in: context) }
    }

    private static func draw(_ layer: PreparedLayer, in context: CGContext) {
        context.saveGState()
        defer { context.restoreGState() }
        context.translateBy(x: layer.offset.x, y: layer.offset.y)
        if let clip = layer.clip {
            context.beginPath()
            context.addPath(clip)
            context.clip()
        }
        // As in SVG, fillStroke paints the fill first and then the stroke.
        if layer.mode != .stroke { paint(layer, stroke: false, in: context) }
        if layer.mode != .fill { paint(layer, stroke: true, in: context) }
    }

    private static func paint(_ layer: PreparedLayer, stroke: Bool, in context: CGContext) {
        context.saveGState()
        defer { context.restoreGState() }
        context.beginPath()
        context.addPath(layer.path)
        if stroke {
            context.setLineWidth(layer.width)
            context.setLineCap(.round)
            context.setLineJoin(.round)
            context.setLineDash(phase: 0, lengths: [])
            context.replacePathWithStrokedPath()
        }
        context.clip()
        layer.paint.draw(in: context)
    }

    private static func makePath(_ commands: [Command], named name: String) throws -> CGPath {
        guard !commands.isEmpty else { throw RenderError.invalid("path \(name) is empty") }
        let path = CGMutablePath()
        var hasMove = false
        for (index, command) in commands.enumerated() {
            let values = command.values
            guard values.allSatisfy({ $0.isFinite }) else {
                throw RenderError.invalid("path \(name), command \(index), has nonfinite coordinates")
            }
            guard command.op == "M" || hasMove else {
                throw RenderError.invalid("path \(name) must begin with M")
            }
            func point(_ index: Int) -> CGPoint {
                CGPoint(x: CGFloat(values[index]), y: CGFloat(values[index + 1]))
            }
            switch (command.op, values.count) {
            case ("M", 2):
                path.move(to: point(0))
                hasMove = true
            case ("L", 2): path.addLine(to: point(0))
            case ("C", 6): path.addCurve(to: point(4), control1: point(0), control2: point(2))
            case ("Q", 4): path.addQuadCurve(to: point(2), control: point(0))
            case ("Z", 0): path.closeSubpath()
            default:
                throw RenderError.invalid("path \(name), command \(index), has unsupported \(command.op)/\(values.count) operands")
            }
        }
        return path
    }

    private static func prepare(_ paint: Paint, named name: String,
                                colorSpace: CGColorSpace) throws -> PreparedPaint {
        let alpha = try opacity(paint.opacity, named: "paint \(name)")
        if paint.kind == "solid" {
            guard let source = paint.color else { throw RenderError.invalid("solid paint \(name) needs a color") }
            return .solid(try color(source, opacity: alpha, colorSpace: colorSpace))
        }
        guard paint.kind == "linear" || paint.kind == "radial" else {
            throw RenderError.invalid("paint \(name) has unsupported kind \(paint.kind)")
        }
        guard let stops = paint.stops, stops.count >= 2 else {
            throw RenderError.invalid("gradient \(name) needs at least two stops")
        }
        var colors: [CGColor] = []
        var locations: [CGFloat] = []
        var previous = -Double.infinity
        for stop in stops {
            guard stop.offset.isFinite, (0...1).contains(stop.offset), stop.offset >= previous else {
                throw RenderError.invalid("gradient \(name) offsets must be ordered between zero and one")
            }
            previous = stop.offset
            let stopAlpha = try opacity(stop.opacity, named: "gradient \(name) stop")
            colors.append(try color(stop.color, opacity: alpha * stopAlpha, colorSpace: colorSpace))
            locations.append(CGFloat(stop.offset))
        }
        guard let gradient = CGGradient(colorsSpace: colorSpace, colors: colors as CFArray, locations: locations) else {
            throw RenderError.invalid("could not create gradient \(name)")
        }
        if paint.kind == "linear" {
            guard let from = paint.from, let to = paint.to else {
                throw RenderError.invalid("linear gradient \(name) needs from and to points")
            }
            let start = try point(from, named: "gradient \(name) from")
            let end = try point(to, named: "gradient \(name) to")
            guard start != end else { throw RenderError.invalid("linear gradient \(name) has no length") }
            return .linear(gradient, start, end)
        }
        guard let center = paint.center, let radius = paint.radius, radius.isFinite, radius > 0 else {
            throw RenderError.invalid("radial gradient \(name) needs a center and finite positive radius")
        }
        return .radial(gradient, try point(center, named: "gradient \(name) center"), CGFloat(radius))
    }

    private static func point(_ values: [Double], named name: String) throws -> CGPoint {
        guard values.count == 2, values.allSatisfy({ $0.isFinite }) else {
            throw RenderError.invalid("\(name) needs two finite coordinates")
        }
        return CGPoint(x: CGFloat(values[0]), y: CGFloat(values[1]))
    }

    private static func opacity(_ value: Double?, named name: String) throws -> CGFloat {
        let alpha = value ?? 1
        guard alpha.isFinite, (0...1).contains(alpha) else {
            throw RenderError.invalid("\(name) opacity must be between zero and one")
        }
        return CGFloat(alpha)
    }

    private static func color(_ source: String, opacity: CGFloat,
                              colorSpace: CGColorSpace) throws -> CGColor {
        guard source.first == "#", source.count == 7 || source.count == 9,
              source.dropFirst().allSatisfy({ "0123456789abcdefABCDEF".contains($0) }),
              let value = UInt32(source.dropFirst(), radix: 16) else {
            throw RenderError.invalid("color \(source) must be #RRGGBB or #RRGGBBAA")
        }
        let rgba = source.count == 9
        let rgb = rgba ? value >> 8 : value
        let alpha = (rgba ? CGFloat(value & 0xFF) / 255 : 1) * opacity
        guard let color = CGColor(colorSpace: colorSpace,
                                  components: [CGFloat((rgb >> 16) & 0xFF) / 255,
                                               CGFloat((rgb >> 8) & 0xFF) / 255,
                                               CGFloat(rgb & 0xFF) / 255, alpha]) else {
            throw RenderError.invalid("could not create sRGB color \(source)")
        }
        return color
    }
}


enum DictaDuoArtwork {
    static let ink: UInt32 = 0x141C26
    static let ivory: UInt32 = 0xFFF8EC
    static let gold: UInt32 = 0xF6C263
    static let copper: UInt32 = 0xC9773C
    static let accent: UInt32 = 0x965222
    static let darkAccent: UInt32 = 0xF6C263
    static let tint: UInt32 = 0xF8E7D2
    static let wordmarkAspectRatio: CGFloat = 551 / 100

    static func markPath(in rect: CGRect) -> CGPath {
        let path = CGMutablePath()
        path.move(to: CGPoint(x: 979.4761, y: 258.37321))
        path.addCurve(to: CGPoint(x: 979.47745, y: 212.51098), control1: CGPoint(x: 979.49571, y: 243.086), control2: CGPoint(x: 979.35138, y: 227.7979))
        path.addCurve(to: CGPoint(x: 977.64161, y: 194.14595), control1: CGPoint(x: 979.51709, y: 207.70519), control2: CGPoint(x: 981.44271, y: 197.72943))
        path.addCurve(to: CGPoint(x: 951.84411, y: 191.2228), control1: CGPoint(x: 971.83496, y: 188.67174), control2: CGPoint(x: 959.43555, y: 191.21137))
        path.addCurve(to: CGPoint(x: 885.91715, y: 191.31784), control1: CGPoint(x: 929.86828, y: 191.25589), control2: CGPoint(x: 907.89312, y: 191.34888))
        path.addCurve(to: CGPoint(x: 716.80018, y: 191.3128), control1: CGPoint(x: 829.54503, y: 191.23821), control2: CGPoint(x: 773.17242, y: 191.3128))
        path.addCurve(to: CGPoint(x: 627.94211, y: 190.38271), control1: CGPoint(x: 687.68778, y: 191.3128), control2: CGPoint(x: 656.84326, y: 194.16868))
        path.addCurve(to: CGPoint(x: 544.81682, y: 156.27719), control1: CGPoint(x: 597.71928, y: 186.4236), control2: CGPoint(x: 568.49192, y: 176.03533))
        path.addCurve(to: CGPoint(x: 341.30318, y: 21.00751), control1: CGPoint(x: 483.60462, y: 105.19233), control2: CGPoint(x: 434.72773, y: 9.12876))
        path.addCurve(to: CGPoint(x: 301.17373, y: 31.47658), control1: CGPoint(x: 327.27519, y: 22.79114), control2: CGPoint(x: 314.27507, y: 26.20435))
        path.addCurve(to: CGPoint(x: 152.12148, y: 187.37596), control1: CGPoint(x: 238.08211, y: 56.86585), control2: CGPoint(x: 206.48457, y: 149.14799))
        path.addCurve(to: CGPoint(x: 68.99619, y: 236.05979), control1: CGPoint(x: 125.52276, y: 206.0801), control2: CGPoint(x: 98.39587, y: 222.34144))
        path.addCurve(to: CGPoint(x: 20.01739, y: 287.0371), control1: CGPoint(x: 46.37491, y: 246.61524), control2: CGPoint(x: 20.81633, y: 258.07904))
        path.addCurve(to: CGPoint(x: 86.19453, y: 346.28632), control1: CGPoint(x: 19.03011, y: 322.82154), control2: CGPoint(x: 60.30928, y: 334.23813))
        path.addCurve(to: CGPoint(x: 123.45759, y: 369.39396), control1: CGPoint(x: 99.36095, y: 352.41458), control2: CGPoint(x: 111.19685, y: 361.71139))
        path.addCurve(to: CGPoint(x: 272.50983, y: 479.26707), control1: CGPoint(x: 177.83679, y: 403.46792), control2: CGPoint(x: 202.55028, y: 468.54309))
        path.addCurve(to: CGPoint(x: 541.95043, y: 323.7636), control1: CGPoint(x: 400.66092, y: 498.91113), control2: CGPoint(x: 422.86679, y: 333.59753))
        path.addCurve(to: CGPoint(x: 656.606, y: 323.39897), control1: CGPoint(x: 579.74173, y: 320.64279), control2: CGPoint(x: 618.69456, y: 323.32355))
        path.addCurve(to: CGPoint(x: 862.98604, y: 323.35032), control1: CGPoint(x: 725.39846, y: 323.53582), control2: CGPoint(x: 794.19318, y: 323.32722))
        path.addCurve(to: CGPoint(x: 946.11133, y: 323.3741), control1: CGPoint(x: 890.69454, y: 323.35963), control2: CGPoint(x: 918.40304, y: 323.48088))
        path.addCurve(to: CGPoint(x: 976.94946, y: 321.43378), control1: CGPoint(x: 954.10643, y: 323.34329), control2: CGPoint(x: 970.47227, y: 326.37282))
        path.addCurve(to: CGPoint(x: 979.45493, y: 304.23544), control1: CGPoint(x: 981.16351, y: 318.22044), control2: CGPoint(x: 979.39605, y: 308.92551))
        path.addCurve(to: CGPoint(x: 979.4761, y: 258.37321), control1: CGPoint(x: 979.64683, y: 288.94739), control2: CGPoint(x: 979.4761, y: 273.66168))
        path.closeSubpath()
        let scale = min(rect.width / 1000, rect.height / 500.88697)
        var transform = CGAffineTransform(a: scale, b: 0, c: 0, d: scale,
                                          tx: rect.minX + (rect.width - 1000 * scale) / 2,
                                          ty: rect.minY + (rect.height - 500.88697 * scale) / 2)
        return path.copy(using: &transform) ?? path
    }

    static func smallMarkPath(in rect: CGRect) -> CGPath {
        let path = CGMutablePath()
        path.move(to: CGPoint(x: 22.987994, y: 12.181723))
        path.addCurve(to: CGPoint(x: 22.988025, y: 11.130713), control1: CGPoint(x: 22.988443, y: 11.831391), control2: CGPoint(x: 22.985136, y: 11.481039))
        path.addCurve(to: CGPoint(x: 22.945954, y: 10.709848), control1: CGPoint(x: 22.988933, y: 11.020581), control2: CGPoint(x: 23.033062, y: 10.79197))
        path.addCurve(to: CGPoint(x: 22.354761, y: 10.642859), control1: CGPoint(x: 22.812884, y: 10.584398), control2: CGPoint(x: 22.528731, y: 10.642597))
        path.addCurve(to: CGPoint(x: 20.843935, y: 10.645037), control1: CGPoint(x: 21.851148, y: 10.643618), control2: CGPoint(x: 21.347551, y: 10.645749))
        path.addCurve(to: CGPoint(x: 16.968337, y: 10.644922), control1: CGPoint(x: 19.552074, y: 10.643212), control2: CGPoint(x: 18.260201, y: 10.644922))
        path.addCurve(to: CGPoint(x: 14.932007, y: 10.623607), control1: CGPoint(x: 16.301178, y: 10.644922), control2: CGPoint(x: 15.594325, y: 10.710369))
        path.addCurve(to: CGPoint(x: 13.027052, y: 9.842022), control1: CGPoint(x: 14.2394, y: 10.532878), control2: CGPoint(x: 13.569607, y: 10.294813))
        path.addCurve(to: CGPoint(x: 8.363198, y: 6.742092), control1: CGPoint(x: 11.624273, y: 8.671328), control2: CGPoint(x: 10.504177, y: 6.469871))
        path.addCurve(to: CGPoint(x: 7.443565, y: 6.982008), control1: CGPoint(x: 8.041723, y: 6.782967), control2: CGPoint(x: 7.743804, y: 6.861186))
        path.addCurve(to: CGPoint(x: 4.027784, y: 10.554703), control1: CGPoint(x: 5.997715, y: 7.563846), control2: CGPoint(x: 5.273605, y: 9.678645))
        path.addCurve(to: CGPoint(x: 2.122829, y: 11.670374), control1: CGPoint(x: 3.41823, y: 10.983339), control2: CGPoint(x: 2.796572, y: 11.355995))
        path.addCurve(to: CGPoint(x: 1.000399, y: 12.838604), control1: CGPoint(x: 1.604425, y: 11.912269), control2: CGPoint(x: 1.018708, y: 12.174981))
        path.addCurve(to: CGPoint(x: 2.516958, y: 14.196398), control1: CGPoint(x: 0.977773, y: 13.658664), control2: CGPoint(x: 1.923754, y: 13.920294))
        path.addCurve(to: CGPoint(x: 3.370903, y: 14.725948), control1: CGPoint(x: 2.818688, y: 14.336838), control2: CGPoint(x: 3.089928, y: 14.549889))
        path.addCurve(to: CGPoint(x: 6.786684, y: 17.243874), control1: CGPoint(x: 4.617093, y: 15.50681), control2: CGPoint(x: 5.183444, y: 16.998116))
        path.addCurve(to: CGPoint(x: 12.961364, y: 13.680253), control1: CGPoint(x: 9.723479, y: 17.69405), control2: CGPoint(x: 10.232364, y: 13.905614))
        path.addCurve(to: CGPoint(x: 15.588888, y: 13.671897), control1: CGPoint(x: 13.827415, y: 13.608734), control2: CGPoint(x: 14.720084, y: 13.670168))
        path.addCurve(to: CGPoint(x: 20.31843, y: 13.670782), control1: CGPoint(x: 17.165381, y: 13.675033), control2: CGPoint(x: 18.741927, y: 13.670252))
        path.addCurve(to: CGPoint(x: 22.223385, y: 13.671327), control1: CGPoint(x: 20.953417, y: 13.670995), control2: CGPoint(x: 21.588403, y: 13.673774))
        path.addCurve(to: CGPoint(x: 22.930092, y: 13.626861), control1: CGPoint(x: 22.406606, y: 13.670621), control2: CGPoint(x: 22.781656, y: 13.740047))
        path.addCurve(to: CGPoint(x: 22.987509, y: 13.232732), control1: CGPoint(x: 23.026664, y: 13.553222), control2: CGPoint(x: 22.986159, y: 13.340213))
        path.addCurve(to: CGPoint(x: 22.987994, y: 12.181723), control1: CGPoint(x: 22.991907, y: 12.882381), control2: CGPoint(x: 22.987994, y: 12.532084))
        path.closeSubpath()
        let scale = min(rect.width / 24, rect.height / 24)
        var transform = CGAffineTransform(a: scale, b: 0, c: 0, d: scale,
                                          tx: rect.minX + (rect.width - 24 * scale) / 2,
                                          ty: rect.minY + (rect.height - 24 * scale) / 2)
        return path.copy(using: &transform) ?? path
    }

    static func wordmarkPath(in rect: CGRect) -> CGPath {
        let path = CGMutablePath()
        path.move(to: CGPoint(x: 75.8366, y: 50.8093))
        path.addCurve(to: CGPoint(x: 70.1089, y: 76.3346), control1: CGPoint(x: 75.8366, y: 61.0195), control2: CGPoint(x: 73.9274, y: 69.5279))
        path.addCurve(to: CGPoint(x: 53.9222, y: 91.6498), control1: CGPoint(x: 66.2905, y: 83.1414), control2: CGPoint(x: 60.8949, y: 88.2464))
        path.addCurve(to: CGPoint(x: 29.144, y: 96.7549), control1: CGPoint(x: 46.9494, y: 95.0532), control2: CGPoint(x: 38.69, y: 96.7549))
        path.addLine(to: CGPoint(x: 2, y: 96.7549))
        path.addLine(to: CGPoint(x: 2, y: 7.8521))
        path.addLine(to: CGPoint(x: 31.3852, y: 7.8521))
        path.addCurve(to: CGPoint(x: 64.07, y: 18.8716), control1: CGPoint(x: 45.3307, y: 7.8521), control2: CGPoint(x: 56.2257, y: 11.5253))
        path.addCurve(to: CGPoint(x: 75.8366, y: 50.8093), control1: CGPoint(x: 71.9144, y: 26.2179), control2: CGPoint(x: 75.8366, y: 36.8638))
        path.closeSubpath()
        path.move(to: CGPoint(x: 55.9144, y: 51.5564))
        path.addCurve(to: CGPoint(x: 49.5642, y: 30.3268), control1: CGPoint(x: 55.9144, y: 42.0104), control2: CGPoint(x: 53.7977, y: 34.9339))
        path.addCurve(to: CGPoint(x: 30.8872, y: 23.4163), control1: CGPoint(x: 45.3307, y: 25.7198), control2: CGPoint(x: 39.1051, y: 23.4163))
        path.addLine(to: CGPoint(x: 21.0506, y: 23.4163))
        path.addLine(to: CGPoint(x: 21.0506, y: 81.0661))
        path.addLine(to: CGPoint(x: 29.0195, y: 81.0661))
        path.addCurve(to: CGPoint(x: 55.9144, y: 51.5564), control1: CGPoint(x: 46.9494, y: 81.0661), control2: CGPoint(x: 55.9144, y: 71.2296))
        path.closeSubpath()
        path.move(to: CGPoint(x: 100.4903, y: 2))
        path.addCurve(to: CGPoint(x: 107.6498, y: 3.93), control1: CGPoint(x: 103.2296, y: 2), control2: CGPoint(x: 105.6161, y: 2.6433))
        path.addCurve(to: CGPoint(x: 110.7004, y: 11.214), control1: CGPoint(x: 109.6835, y: 5.2166), control2: CGPoint(x: 110.7004, y: 7.6446))
        path.addCurve(to: CGPoint(x: 107.6498, y: 18.3113), control1: CGPoint(x: 110.7004, y: 14.6174), control2: CGPoint(x: 109.6835, y: 16.9831))
        path.addCurve(to: CGPoint(x: 100.4903, y: 20.3035), control1: CGPoint(x: 105.6161, y: 19.6394), control2: CGPoint(x: 103.2296, y: 20.3035))
        path.addCurve(to: CGPoint(x: 93.2685, y: 18.3113), control1: CGPoint(x: 97.668, y: 20.3035), control2: CGPoint(x: 95.2607, y: 19.6394))
        path.addCurve(to: CGPoint(x: 90.2802, y: 11.214), control1: CGPoint(x: 91.2763, y: 16.9831), control2: CGPoint(x: 90.2802, y: 14.6174))
        path.addCurve(to: CGPoint(x: 93.2685, y: 3.93), control1: CGPoint(x: 90.2802, y: 7.6446), control2: CGPoint(x: 91.2763, y: 5.2166))
        path.addCurve(to: CGPoint(x: 100.4903, y: 2), control1: CGPoint(x: 95.2607, y: 2.6433), control2: CGPoint(x: 97.668, y: 2))
        path.closeSubpath()
        path.move(to: CGPoint(x: 109.8288, y: 28.7704))
        path.addLine(to: CGPoint(x: 109.8288, y: 96.7549))
        path.addLine(to: CGPoint(x: 91.0272, y: 96.7549))
        path.addLine(to: CGPoint(x: 91.0272, y: 28.7704))
        path.closeSubpath()
        path.move(to: CGPoint(x: 156.5214, y: 98))
        path.addCurve(to: CGPoint(x: 139.2763, y: 94.3268), control1: CGPoint(x: 149.9637, y: 98), control2: CGPoint(x: 144.2153, y: 96.7756))
        path.addCurve(to: CGPoint(x: 127.7588, y: 82.9339), control1: CGPoint(x: 134.3372, y: 91.8781), control2: CGPoint(x: 130.4981, y: 88.0804))
        path.addCurve(to: CGPoint(x: 123.6498, y: 63.1362), control1: CGPoint(x: 125.0195, y: 77.7873), control2: CGPoint(x: 123.6498, y: 71.1881))
        path.addCurve(to: CGPoint(x: 128.1323, y: 42.7782), control1: CGPoint(x: 123.6498, y: 54.8353), control2: CGPoint(x: 125.144, y: 48.0493))
        path.addCurve(to: CGPoint(x: 140.3346, y: 31.1984), control1: CGPoint(x: 131.1206, y: 37.5071), control2: CGPoint(x: 135.1881, y: 33.6472))
        path.addCurve(to: CGPoint(x: 157.8911, y: 27.5253), control1: CGPoint(x: 145.4812, y: 28.7497), control2: CGPoint(x: 151.3333, y: 27.5253))
        path.addCurve(to: CGPoint(x: 169.0973, y: 28.7704), control1: CGPoint(x: 161.7925, y: 27.5253), control2: CGPoint(x: 165.5279, y: 27.9403))
        path.addCurve(to: CGPoint(x: 178.5603, y: 32.1323), control1: CGPoint(x: 172.6667, y: 29.6005), control2: CGPoint(x: 175.821, y: 30.7211))
        path.addLine(to: CGPoint(x: 172.9572, y: 46.3268))
        path.addCurve(to: CGPoint(x: 165.4241, y: 43.6498), control1: CGPoint(x: 170.4669, y: 45.2477), control2: CGPoint(x: 167.9559, y: 44.3554))
        path.addCurve(to: CGPoint(x: 157.8911, y: 42.5914), control1: CGPoint(x: 162.8923, y: 42.9442), control2: CGPoint(x: 160.3813, y: 42.5914))
        path.addCurve(to: CGPoint(x: 146.7471, y: 47.6965), control1: CGPoint(x: 153.0765, y: 42.5914), control2: CGPoint(x: 149.3619, y: 44.2931))
        path.addCurve(to: CGPoint(x: 142.8249, y: 63.0117), control1: CGPoint(x: 144.1323, y: 51.0999), control2: CGPoint(x: 142.8249, y: 56.2049))
        path.addCurve(to: CGPoint(x: 146.7471, y: 77.9533), control1: CGPoint(x: 142.8249, y: 69.7354), control2: CGPoint(x: 144.1323, y: 74.716))
        path.addCurve(to: CGPoint(x: 157.642, y: 82.8093), control1: CGPoint(x: 149.3619, y: 81.1907), control2: CGPoint(x: 152.9935, y: 82.8093))
        path.addCurve(to: CGPoint(x: 167.7276, y: 81.3774), control1: CGPoint(x: 161.1284, y: 82.8093), control2: CGPoint(x: 164.4903, y: 82.332))
        path.addCurve(to: CGPoint(x: 176.6926, y: 77.5798), control1: CGPoint(x: 170.965, y: 80.4228), control2: CGPoint(x: 173.9533, y: 79.1569))
        path.addLine(to: CGPoint(x: 176.6926, y: 92.8949))
        path.addCurve(to: CGPoint(x: 167.9144, y: 96.6304), control1: CGPoint(x: 174.0363, y: 94.4721), control2: CGPoint(x: 171.1102, y: 95.7173))
        path.addCurve(to: CGPoint(x: 156.5214, y: 98), control1: CGPoint(x: 164.7185, y: 97.5435), control2: CGPoint(x: 160.9209, y: 98))
        path.closeSubpath()
        path.move(to: CGPoint(x: 219.8988, y: 83.1829))
        path.addCurve(to: CGPoint(x: 225.8755, y: 82.5603), control1: CGPoint(x: 221.9741, y: 83.1829), control2: CGPoint(x: 223.9663, y: 82.9754))
        path.addCurve(to: CGPoint(x: 231.6031, y: 81.0661), control1: CGPoint(x: 227.7847, y: 82.1453), control2: CGPoint(x: 229.6939, y: 81.6472))
        path.addLine(to: CGPoint(x: 231.6031, y: 94.8872))
        path.addCurve(to: CGPoint(x: 224.1946, y: 97.0661), control1: CGPoint(x: 229.6109, y: 95.7173), control2: CGPoint(x: 227.1414, y: 96.4436))
        path.addCurve(to: CGPoint(x: 214.5447, y: 98), control1: CGPoint(x: 221.2477, y: 97.6887), control2: CGPoint(x: 218.0311, y: 98))
        path.addCurve(to: CGPoint(x: 203.6498, y: 96.0078), control1: CGPoint(x: 210.4773, y: 98), control2: CGPoint(x: 206.8457, y: 97.3359))
        path.addCurve(to: CGPoint(x: 196.0545, y: 89.0973), control1: CGPoint(x: 200.454, y: 94.6796), control2: CGPoint(x: 197.9222, y: 92.3761))
        path.addCurve(to: CGPoint(x: 193.2529, y: 75.463), control1: CGPoint(x: 194.1868, y: 85.8184), control2: CGPoint(x: 193.2529, y: 81.2737))
        path.addLine(to: CGPoint(x: 193.2529, y: 42.716))
        path.addLine(to: CGPoint(x: 184.4125, y: 42.716))
        path.addLine(to: CGPoint(x: 184.4125, y: 34.8716))
        path.addLine(to: CGPoint(x: 194.6226, y: 28.6459))
        path.addLine(to: CGPoint(x: 199.9767, y: 14.3268))
        path.addLine(to: CGPoint(x: 211.8054, y: 14.3268))
        path.addLine(to: CGPoint(x: 211.8054, y: 28.7704))
        path.addLine(to: CGPoint(x: 230.856, y: 28.7704))
        path.addLine(to: CGPoint(x: 230.856, y: 42.716))
        path.addLine(to: CGPoint(x: 211.8054, y: 42.716))
        path.addLine(to: CGPoint(x: 211.8054, y: 75.463))
        path.addCurve(to: CGPoint(x: 214.0467, y: 81.2529), control1: CGPoint(x: 211.8054, y: 78.0363), control2: CGPoint(x: 212.5525, y: 79.9663))
        path.addCurve(to: CGPoint(x: 219.8988, y: 83.1829), control1: CGPoint(x: 215.5409, y: 82.5396), control2: CGPoint(x: 217.4916, y: 83.1829))
        path.closeSubpath()
        path.move(to: CGPoint(x: 274.4358, y: 27.5253))
        path.addCurve(to: CGPoint(x: 293.9222, y: 33.5642), control1: CGPoint(x: 282.9027, y: 27.5253), control2: CGPoint(x: 289.3982, y: 29.5383))
        path.addCurve(to: CGPoint(x: 300.7082, y: 51.4319), control1: CGPoint(x: 298.4462, y: 37.5901), control2: CGPoint(x: 300.7082, y: 43.546))
        path.addLine(to: CGPoint(x: 300.7082, y: 96.7549))
        path.addLine(to: CGPoint(x: 287.6342, y: 96.7549))
        path.addLine(to: CGPoint(x: 284.0233, y: 87.5409))
        path.addLine(to: CGPoint(x: 283.5253, y: 87.5409))
        path.addCurve(to: CGPoint(x: 274.249, y: 95.5097), control1: CGPoint(x: 280.537, y: 91.1933), control2: CGPoint(x: 277.4449, y: 93.8495))
        path.addCurve(to: CGPoint(x: 260.8638, y: 98), control1: CGPoint(x: 271.0532, y: 97.1699), control2: CGPoint(x: 266.5914, y: 98))
        path.addCurve(to: CGPoint(x: 245.9222, y: 92.7704), control1: CGPoint(x: 254.8872, y: 98), control2: CGPoint(x: 249.9066, y: 96.2568))
        path.addCurve(to: CGPoint(x: 239.9455, y: 76.7082), control1: CGPoint(x: 241.9377, y: 89.284), control2: CGPoint(x: 239.9455, y: 83.93))
        path.addCurve(to: CGPoint(x: 247.6654, y: 60.7082), control1: CGPoint(x: 239.9455, y: 69.6524), control2: CGPoint(x: 242.5188, y: 64.3191))
        path.addCurve(to: CGPoint(x: 270.7004, y: 54.6693), control1: CGPoint(x: 252.8119, y: 57.0973), control2: CGPoint(x: 260.4903, y: 55.0843))
        path.addLine(to: CGPoint(x: 282.0311, y: 54.2957))
        path.addLine(to: CGPoint(x: 282.0311, y: 52.179))
        path.addCurve(to: CGPoint(x: 279.2296, y: 43.6498), control1: CGPoint(x: 282.0311, y: 48.1115), control2: CGPoint(x: 281.0973, y: 45.2685))
        path.addCurve(to: CGPoint(x: 271.572, y: 41.2218), control1: CGPoint(x: 277.3619, y: 42.0311), control2: CGPoint(x: 274.8093, y: 41.2218))
        path.addCurve(to: CGPoint(x: 262.1089, y: 42.716), control1: CGPoint(x: 268.5006, y: 41.2218), control2: CGPoint(x: 265.3463, y: 41.7198))
        path.addCurve(to: CGPoint(x: 252.5214, y: 46.3268), control1: CGPoint(x: 258.8716, y: 43.7121), control2: CGPoint(x: 255.6757, y: 44.9157))
        path.addLine(to: CGPoint(x: 247.0428, y: 33.5019))
        path.addCurve(to: CGPoint(x: 259.3074, y: 29.144), control1: CGPoint(x: 250.6122, y: 31.6757), control2: CGPoint(x: 254.7004, y: 30.2231))
        path.addCurve(to: CGPoint(x: 274.4358, y: 27.5253), control1: CGPoint(x: 263.9144, y: 28.0649), control2: CGPoint(x: 268.9572, y: 27.5253))
        path.closeSubpath()
        path.move(to: CGPoint(x: 274.9339, y: 65.6265))
        path.addCurve(to: CGPoint(x: 262.5447, y: 68.4903), control1: CGPoint(x: 268.9572, y: 65.7925), control2: CGPoint(x: 264.8275, y: 66.7471))
        path.addCurve(to: CGPoint(x: 259.1206, y: 75.8366), control1: CGPoint(x: 260.262, y: 70.2335), control2: CGPoint(x: 259.1206, y: 72.6822))
        path.addCurve(to: CGPoint(x: 261.5486, y: 82.249), control1: CGPoint(x: 259.1206, y: 78.7419), control2: CGPoint(x: 259.93, y: 80.8794))
        path.addCurve(to: CGPoint(x: 268.0856, y: 84.3035), control1: CGPoint(x: 263.1673, y: 83.6187), control2: CGPoint(x: 265.3463, y: 84.3035))
        path.addCurve(to: CGPoint(x: 277.9844, y: 80.8171), control1: CGPoint(x: 271.987, y: 84.3035), control2: CGPoint(x: 275.2866, y: 83.1414))
        path.addCurve(to: CGPoint(x: 282.0311, y: 70.856), control1: CGPoint(x: 280.6822, y: 78.4929), control2: CGPoint(x: 282.0311, y: 75.1725))
        path.addLine(to: CGPoint(x: 282.0311, y: 65.2529))
        path.closeSubpath()
        path.move(to: CGPoint(x: 391.7276, y: 50.8093))
        path.addCurve(to: CGPoint(x: 386, y: 76.3346), control1: CGPoint(x: 391.7276, y: 61.0195), control2: CGPoint(x: 389.8184, y: 69.5279))
        path.addCurve(to: CGPoint(x: 369.8132, y: 91.6498), control1: CGPoint(x: 382.1816, y: 83.1414), control2: CGPoint(x: 376.786, y: 88.2464))
        path.addCurve(to: CGPoint(x: 345.035, y: 96.7549), control1: CGPoint(x: 362.8405, y: 95.0532), control2: CGPoint(x: 354.5811, y: 96.7549))
        path.addLine(to: CGPoint(x: 317.8911, y: 96.7549))
        path.addLine(to: CGPoint(x: 317.8911, y: 7.8521))
        path.addLine(to: CGPoint(x: 347.2763, y: 7.8521))
        path.addCurve(to: CGPoint(x: 379.9611, y: 18.8716), control1: CGPoint(x: 361.2218, y: 7.8521), control2: CGPoint(x: 372.1167, y: 11.5253))
        path.addCurve(to: CGPoint(x: 391.7276, y: 50.8093), control1: CGPoint(x: 387.8054, y: 26.2179), control2: CGPoint(x: 391.7276, y: 36.8638))
        path.closeSubpath()
        path.move(to: CGPoint(x: 371.8054, y: 51.5564))
        path.addCurve(to: CGPoint(x: 365.4553, y: 30.3268), control1: CGPoint(x: 371.8054, y: 42.0104), control2: CGPoint(x: 369.6887, y: 34.9339))
        path.addCurve(to: CGPoint(x: 346.7782, y: 23.4163), control1: CGPoint(x: 361.2218, y: 25.7198), control2: CGPoint(x: 354.9961, y: 23.4163))
        path.addLine(to: CGPoint(x: 336.9416, y: 23.4163))
        path.addLine(to: CGPoint(x: 336.9416, y: 81.0661))
        path.addLine(to: CGPoint(x: 344.9105, y: 81.0661))
        path.addCurve(to: CGPoint(x: 371.8054, y: 51.5564), control1: CGPoint(x: 362.8405, y: 81.0661), control2: CGPoint(x: 371.8054, y: 71.2296))
        path.closeSubpath()
        path.move(to: CGPoint(x: 469.1751, y: 28.7704))
        path.addLine(to: CGPoint(x: 469.1751, y: 96.7549))
        path.addLine(to: CGPoint(x: 454.7315, y: 96.7549))
        path.addLine(to: CGPoint(x: 452.3658, y: 88.0389))
        path.addLine(to: CGPoint(x: 451.2451, y: 88.0389))
        path.addCurve(to: CGPoint(x: 442.4047, y: 95.6342), control1: CGPoint(x: 449.0869, y: 91.5253), control2: CGPoint(x: 446.1401, y: 94.0571))
        path.addCurve(to: CGPoint(x: 430.3268, y: 98), control1: CGPoint(x: 438.6693, y: 97.2114), control2: CGPoint(x: 434.6433, y: 98))
        path.addCurve(to: CGPoint(x: 412.8327, y: 92.0856), control1: CGPoint(x: 423.1051, y: 98), control2: CGPoint(x: 417.2737, y: 96.0285))
        path.addCurve(to: CGPoint(x: 406.1712, y: 73.0973), control1: CGPoint(x: 408.3917, y: 88.1427), control2: CGPoint(x: 406.1712, y: 81.8132))
        path.addLine(to: CGPoint(x: 406.1712, y: 28.7704))
        path.addLine(to: CGPoint(x: 425.0973, y: 28.7704))
        path.addLine(to: CGPoint(x: 425.0973, y: 68.3658))
        path.addCurve(to: CGPoint(x: 427.6498, y: 79.2607), control1: CGPoint(x: 425.0973, y: 73.1803), control2: CGPoint(x: 425.9481, y: 76.8119))
        path.addCurve(to: CGPoint(x: 435.8054, y: 82.9339), control1: CGPoint(x: 429.3515, y: 81.7095), control2: CGPoint(x: 432.07, y: 82.9339))
        path.addCurve(to: CGPoint(x: 447.323, y: 77.2062), control1: CGPoint(x: 441.4501, y: 82.9339), control2: CGPoint(x: 445.2892, y: 81.0246))
        path.addCurve(to: CGPoint(x: 450.3735, y: 60.6459), control1: CGPoint(x: 449.3567, y: 73.3878), control2: CGPoint(x: 450.3735, y: 67.8677))
        path.addLine(to: CGPoint(x: 450.3735, y: 28.7704))
        path.closeSubpath()
        path.move(to: CGPoint(x: 548.9883, y: 62.6381))
        path.addCurve(to: CGPoint(x: 540.0856, y: 88.786), control1: CGPoint(x: 548.9883, y: 73.9274), control2: CGPoint(x: 546.0208, y: 82.6433))
        path.addCurve(to: CGPoint(x: 515.8677, y: 98), control1: CGPoint(x: 534.1505, y: 94.9287), control2: CGPoint(x: 526.0778, y: 98))
        path.addCurve(to: CGPoint(x: 498.8716, y: 93.8911), control1: CGPoint(x: 509.476, y: 98), control2: CGPoint(x: 503.8106, y: 96.6304))
        path.addCurve(to: CGPoint(x: 487.2296, y: 81.8755), control1: CGPoint(x: 493.9326, y: 91.1518), control2: CGPoint(x: 490.0519, y: 87.1466))
        path.addCurve(to: CGPoint(x: 482.9961, y: 62.6381), control1: CGPoint(x: 484.4073, y: 76.6044), control2: CGPoint(x: 482.9961, y: 70.192))
        path.addCurve(to: CGPoint(x: 491.8988, y: 36.6148), control1: CGPoint(x: 482.9961, y: 51.3489), control2: CGPoint(x: 485.9637, y: 42.6744))
        path.addCurve(to: CGPoint(x: 516.2412, y: 27.5253), control1: CGPoint(x: 497.834, y: 30.5551), control2: CGPoint(x: 505.9481, y: 27.5253))
        path.addCurve(to: CGPoint(x: 533.1751, y: 31.572), control1: CGPoint(x: 522.6329, y: 27.5253), control2: CGPoint(x: 528.2776, y: 28.8742))
        path.addCurve(to: CGPoint(x: 544.7549, y: 43.463), control1: CGPoint(x: 538.0726, y: 34.2698), control2: CGPoint(x: 541.9326, y: 38.2335))
        path.addCurve(to: CGPoint(x: 548.9883, y: 62.6381), control1: CGPoint(x: 547.5772, y: 48.6926), control2: CGPoint(x: 548.9883, y: 55.0843))
        path.closeSubpath()
        path.move(to: CGPoint(x: 502.1712, y: 62.6381))
        path.addCurve(to: CGPoint(x: 505.4086, y: 78.1401), control1: CGPoint(x: 502.1712, y: 69.2789), control2: CGPoint(x: 503.2503, y: 74.4462))
        path.addCurve(to: CGPoint(x: 516.1167, y: 83.6809), control1: CGPoint(x: 507.5668, y: 81.834), control2: CGPoint(x: 511.1362, y: 83.6809))
        path.addCurve(to: CGPoint(x: 526.5759, y: 78.1401), control1: CGPoint(x: 520.9313, y: 83.6809), control2: CGPoint(x: 524.4176, y: 81.834))
        path.addCurve(to: CGPoint(x: 529.8132, y: 62.6381), control1: CGPoint(x: 528.7341, y: 74.4462), control2: CGPoint(x: 529.8132, y: 69.2789))
        path.addCurve(to: CGPoint(x: 526.5759, y: 47.1984), control1: CGPoint(x: 529.8132, y: 55.9144), control2: CGPoint(x: 528.7341, y: 50.7678))
        path.addCurve(to: CGPoint(x: 515.9922, y: 41.8444), control1: CGPoint(x: 524.4176, y: 43.6291), control2: CGPoint(x: 520.8898, y: 41.8444))
        path.addCurve(to: CGPoint(x: 505.4086, y: 47.1984), control1: CGPoint(x: 511.0947, y: 41.8444), control2: CGPoint(x: 507.5668, y: 43.6291))
        path.addCurve(to: CGPoint(x: 502.1712, y: 62.6381), control1: CGPoint(x: 503.2503, y: 50.7678), control2: CGPoint(x: 502.1712, y: 55.9144))
        path.closeSubpath()
        let scale = min(rect.width / 551, rect.height / 100)
        var transform = CGAffineTransform(a: scale, b: 0, c: 0, d: scale,
                                          tx: rect.minX + (rect.width - 551 * scale) / 2,
                                          ty: rect.minY + (rect.height - 100 * scale) / 2)
        return path.copy(using: &transform) ?? path
    }

    static func appTilePath(in rect: CGRect) -> CGPath {
        let path = CGMutablePath()
        path.move(to: CGPoint(x: 288, y: 64))
        path.addLine(to: CGPoint(x: 736, y: 64))
        path.addCurve(to: CGPoint(x: 960, y: 288), control1: CGPoint(x: 880, y: 64), control2: CGPoint(x: 960, y: 144))
        path.addLine(to: CGPoint(x: 960, y: 736))
        path.addCurve(to: CGPoint(x: 736, y: 960), control1: CGPoint(x: 960, y: 880), control2: CGPoint(x: 880, y: 960))
        path.addLine(to: CGPoint(x: 288, y: 960))
        path.addCurve(to: CGPoint(x: 64, y: 736), control1: CGPoint(x: 144, y: 960), control2: CGPoint(x: 64, y: 880))
        path.addLine(to: CGPoint(x: 64, y: 288))
        path.addCurve(to: CGPoint(x: 288, y: 64), control1: CGPoint(x: 64, y: 144), control2: CGPoint(x: 144, y: 64))
        path.closeSubpath()
        let scale = min(rect.width / 1024, rect.height / 1024)
        var transform = CGAffineTransform(a: scale, b: 0, c: 0, d: scale,
                                          tx: rect.minX + (rect.width - 1024 * scale) / 2,
                                          ty: rect.minY + (rect.height - 1024 * scale) / 2)
        return path.copy(using: &transform) ?? path
    }

    static func appMarkPath(in rect: CGRect) -> CGPath {
        let path = CGMutablePath()
        path.move(to: CGPoint(x: 887.589612, y: 532.211618))
        path.addCurve(to: CGPoint(x: 887.590669, y: 496.286204), control1: CGPoint(x: 887.604973, y: 520.236637), control2: CGPoint(x: 887.491914, y: 508.260958))
        path.addCurve(to: CGPoint(x: 886.152595, y: 481.900264), control1: CGPoint(x: 887.621721, y: 492.521669), control2: CGPoint(x: 889.130123, y: 484.707324))
        path.addCurve(to: CGPoint(x: 865.944553, y: 479.610463), control1: CGPoint(x: 881.604052, y: 477.612133), control2: CGPoint(x: 871.891181, y: 479.60151))
        path.addCurve(to: CGPoint(x: 814.301767, y: 479.684911), control1: CGPoint(x: 848.730153, y: 479.636384), control2: CGPoint(x: 831.516277, y: 479.709226))
        path.addCurve(to: CGPoint(x: 681.826808, y: 479.680963), control1: CGPoint(x: 770.143607, y: 479.622535), control2: CGPoint(x: 725.985062, y: 479.680963))
        path.addCurve(to: CGPoint(x: 612.221319, y: 478.952393), control1: CGPoint(x: 659.022094, y: 479.680963), control2: CGPoint(x: 634.860554, y: 481.918069))
        path.addCurve(to: CGPoint(x: 547.106509, y: 452.236402), control1: CGPoint(x: 588.546769, y: 475.85109), control2: CGPoint(x: 565.652004, y: 467.713612))
        path.addCurve(to: CGPoint(x: 387.687491, y: 346.275153), control1: CGPoint(x: 499.156952, y: 412.219929), control2: CGPoint(x: 460.870055, y: 336.970132))
        path.addCurve(to: CGPoint(x: 356.252755, y: 354.475924), control1: CGPoint(x: 376.698899, y: 347.67233), control2: CGPoint(x: 366.515471, y: 350.346011))
        path.addCurve(to: CGPoint(x: 239.495159, y: 476.597105), control1: CGPoint(x: 306.830986, y: 374.364186), control2: CGPoint(x: 282.07958, y: 446.651862))
        path.addCurve(to: CGPoint(x: 174.380349, y: 514.732772), control1: CGPoint(x: 218.659495, y: 491.248682), control2: CGPoint(x: 197.410098, y: 503.986731))
        path.addCurve(to: CGPoint(x: 136.013622, y: 554.664998), control1: CGPoint(x: 156.660346, y: 523.001208), control2: CGPoint(x: 136.639458, y: 531.981185))
        path.addCurve(to: CGPoint(x: 187.852382, y: 601.076887), control1: CGPoint(x: 135.240253, y: 582.696143), control2: CGPoint(x: 167.575603, y: 591.639139))
        path.addCurve(to: CGPoint(x: 217.041779, y: 619.177872), control1: CGPoint(x: 198.166077, y: 605.877358), control2: CGPoint(x: 207.437532, y: 613.159859))
        path.addCurve(to: CGPoint(x: 333.799367, y: 705.245142), control1: CGPoint(x: 259.638819, y: 645.869141), control2: CGPoint(x: 278.997719, y: 696.844691))
        path.addCurve(to: CGPoint(x: 544.86117, y: 583.43409), control1: CGPoint(x: 434.184387, y: 720.632989), control2: CGPoint(x: 451.578985, y: 591.137335))
        path.addCurve(to: CGPoint(x: 634.6747, y: 583.148463), control1: CGPoint(x: 574.464355, y: 580.989456), control2: CGPoint(x: 604.977405, y: 583.089384))
        path.addCurve(to: CGPoint(x: 796.339065, y: 583.110354), control1: CGPoint(x: 688.562127, y: 583.255662), control2: CGPoint(x: 742.451324, y: 583.092259))
        path.addCurve(to: CGPoint(x: 861.453875, y: 583.128982), control1: CGPoint(x: 818.044056, y: 583.117647), control2: CGPoint(x: 839.749048, y: 583.212626))
        path.addCurve(to: CGPoint(x: 885.61041, y: 581.609064), control1: CGPoint(x: 867.716703, y: 583.104847), control2: CGPoint(x: 880.536611, y: 585.477979))
        path.addCurve(to: CGPoint(x: 887.573028, y: 568.137031), control1: CGPoint(x: 888.911416, y: 579.091948), control2: CGPoint(x: 887.526906, y: 571.81092))
        path.addCurve(to: CGPoint(x: 887.589612, y: 532.211618), control1: CGPoint(x: 887.72335, y: 556.161392), control2: CGPoint(x: 887.589612, y: 544.187586))
        path.closeSubpath()
        let scale = min(rect.width / 1024, rect.height / 1024)
        var transform = CGAffineTransform(a: scale, b: 0, c: 0, d: scale,
                                          tx: rect.minX + (rect.width - 1024 * scale) / 2,
                                          ty: rect.minY + (rect.height - 1024 * scale) / 2)
        return path.copy(using: &transform) ?? path
    }

    // Generation validates this model before embedding it.
    private static let iconModel = try! JSONDecoder().decode(BrandIconRenderer.Model.self, from: Data(#"""
    {
      "canvas": 1024,
      "paths": {
        "tile": [
          {
            "op": "M",
            "values": [
              288,
              64
            ]
          },
          {
            "op": "L",
            "values": [
              736,
              64
            ]
          },
          {
            "op": "C",
            "values": [
              880,
              64,
              960,
              144,
              960,
              288
            ]
          },
          {
            "op": "L",
            "values": [
              960,
              736
            ]
          },
          {
            "op": "C",
            "values": [
              960,
              880,
              880,
              960,
              736,
              960
            ]
          },
          {
            "op": "L",
            "values": [
              288,
              960
            ]
          },
          {
            "op": "C",
            "values": [
              144,
              960,
              64,
              880,
              64,
              736
            ]
          },
          {
            "op": "L",
            "values": [
              64,
              288
            ]
          },
          {
            "op": "C",
            "values": [
              64,
              144,
              144,
              64,
              288,
              64
            ]
          },
          {
            "op": "Z",
            "values": []
          }
        ],
        "tileRim": [
          {
            "op": "M",
            "values": [
              288.896,
              65.792
            ]
          },
          {
            "op": "L",
            "values": [
              735.104,
              65.792
            ]
          },
          {
            "op": "C",
            "values": [
              878.528,
              65.792,
              958.208,
              145.472,
              958.208,
              288.896
            ]
          },
          {
            "op": "L",
            "values": [
              958.208,
              735.104
            ]
          },
          {
            "op": "C",
            "values": [
              958.208,
              878.528,
              878.528,
              958.208,
              735.104,
              958.208
            ]
          },
          {
            "op": "L",
            "values": [
              288.896,
              958.208
            ]
          },
          {
            "op": "C",
            "values": [
              145.472,
              958.208,
              65.792,
              878.528,
              65.792,
              735.104
            ]
          },
          {
            "op": "L",
            "values": [
              65.792,
              288.896
            ]
          },
          {
            "op": "C",
            "values": [
              65.792,
              145.472,
              145.472,
              65.792,
              288.896,
              65.792
            ]
          },
          {
            "op": "Z",
            "values": []
          }
        ],
        "tileSoftRim": [
          {
            "op": "M",
            "values": [
              290.24,
              68.48
            ]
          },
          {
            "op": "L",
            "values": [
              733.76,
              68.48
            ]
          },
          {
            "op": "C",
            "values": [
              876.32,
              68.48,
              955.52,
              147.68,
              955.52,
              290.24
            ]
          },
          {
            "op": "L",
            "values": [
              955.52,
              733.76
            ]
          },
          {
            "op": "C",
            "values": [
              955.52,
              876.32,
              876.32,
              955.52,
              733.76,
              955.52
            ]
          },
          {
            "op": "L",
            "values": [
              290.24,
              955.52
            ]
          },
          {
            "op": "C",
            "values": [
              147.68,
              955.52,
              68.48,
              876.32,
              68.48,
              733.76
            ]
          },
          {
            "op": "L",
            "values": [
              68.48,
              290.24
            ]
          },
          {
            "op": "C",
            "values": [
              68.48,
              147.68,
              147.68,
              68.48,
              290.24,
              68.48
            ]
          },
          {
            "op": "Z",
            "values": []
          }
        ],
        "mark": [
          {
            "op": "M",
            "values": [
              887.589612,
              532.211618
            ]
          },
          {
            "op": "C",
            "values": [
              887.604973,
              520.236637,
              887.491914,
              508.260958,
              887.590669,
              496.286204
            ]
          },
          {
            "op": "C",
            "values": [
              887.621721,
              492.521669,
              889.130123,
              484.707324,
              886.152595,
              481.900264
            ]
          },
          {
            "op": "C",
            "values": [
              881.604052,
              477.612133,
              871.891181,
              479.60151,
              865.944553,
              479.610463
            ]
          },
          {
            "op": "C",
            "values": [
              848.730153,
              479.636384,
              831.516277,
              479.709226,
              814.301767,
              479.684911
            ]
          },
          {
            "op": "C",
            "values": [
              770.143607,
              479.622535,
              725.985062,
              479.680963,
              681.826808,
              479.680963
            ]
          },
          {
            "op": "C",
            "values": [
              659.022094,
              479.680963,
              634.860554,
              481.918069,
              612.221319,
              478.952393
            ]
          },
          {
            "op": "C",
            "values": [
              588.546769,
              475.85109,
              565.652004,
              467.713612,
              547.106509,
              452.236402
            ]
          },
          {
            "op": "C",
            "values": [
              499.156952,
              412.219929,
              460.870055,
              336.970132,
              387.687491,
              346.275153
            ]
          },
          {
            "op": "C",
            "values": [
              376.698899,
              347.67233,
              366.515471,
              350.346011,
              356.252755,
              354.475924
            ]
          },
          {
            "op": "C",
            "values": [
              306.830986,
              374.364186,
              282.07958,
              446.651862,
              239.495159,
              476.597105
            ]
          },
          {
            "op": "C",
            "values": [
              218.659495,
              491.248682,
              197.410098,
              503.986731,
              174.380349,
              514.732772
            ]
          },
          {
            "op": "C",
            "values": [
              156.660346,
              523.001208,
              136.639458,
              531.981185,
              136.013622,
              554.664998
            ]
          },
          {
            "op": "C",
            "values": [
              135.240253,
              582.696143,
              167.575603,
              591.639139,
              187.852382,
              601.076887
            ]
          },
          {
            "op": "C",
            "values": [
              198.166077,
              605.877358,
              207.437532,
              613.159859,
              217.041779,
              619.177872
            ]
          },
          {
            "op": "C",
            "values": [
              259.638819,
              645.869141,
              278.997719,
              696.844691,
              333.799367,
              705.245142
            ]
          },
          {
            "op": "C",
            "values": [
              434.184387,
              720.632989,
              451.578985,
              591.137335,
              544.86117,
              583.43409
            ]
          },
          {
            "op": "C",
            "values": [
              574.464355,
              580.989456,
              604.977405,
              583.089384,
              634.6747,
              583.148463
            ]
          },
          {
            "op": "C",
            "values": [
              688.562127,
              583.255662,
              742.451324,
              583.092259,
              796.339065,
              583.110354
            ]
          },
          {
            "op": "C",
            "values": [
              818.044056,
              583.117647,
              839.749048,
              583.212626,
              861.453875,
              583.128982
            ]
          },
          {
            "op": "C",
            "values": [
              867.716703,
              583.104847,
              880.536611,
              585.477979,
              885.61041,
              581.609064
            ]
          },
          {
            "op": "C",
            "values": [
              888.911416,
              579.091948,
              887.526906,
              571.81092,
              887.573028,
              568.137031
            ]
          },
          {
            "op": "C",
            "values": [
              887.72335,
              556.161392,
              887.589612,
              544.187586,
              887.589612,
              532.211618
            ]
          },
          {
            "op": "Z",
            "values": []
          }
        ]
      },
      "paints": {
        "tileGradient": {
          "kind": "linear",
          "from": [
            80,
            80
          ],
          "to": [
            920,
            960
          ],
          "stops": [
            {
              "offset": 0,
              "color": "#485562"
            },
            {
              "offset": 0.34,
              "color": "#323E4C"
            },
            {
              "offset": 0.74,
              "color": "#202A37"
            },
            {
              "offset": 1,
              "color": "#131B25"
            }
          ]
        },
        "tileLight": {
          "kind": "radial",
          "center": [
            240,
            100
          ],
          "radius": 880,
          "stops": [
            {
              "offset": 0,
              "color": "#EAF2FF",
              "opacity": 0.12
            },
            {
              "offset": 0.7,
              "color": "#D9E4FF",
              "opacity": 0.015
            },
            {
              "offset": 1,
              "color": "#FFFFFF",
              "opacity": 0
            }
          ]
        },
        "tileRim": {
          "kind": "linear",
          "from": [
            80,
            64
          ],
          "to": [
            800,
            960
          ],
          "stops": [
            {
              "offset": 0,
              "color": "#DEE8F1",
              "opacity": 0.5
            },
            {
              "offset": 0.24,
              "color": "#B9C7D7",
              "opacity": 0.08
            },
            {
              "offset": 0.72,
              "color": "#B9C7D7",
              "opacity": 0
            },
            {
              "offset": 1,
              "color": "#687786",
              "opacity": 0.14
            }
          ]
        },
        "tileSoftRim": {
          "kind": "linear",
          "from": [
            80,
            64
          ],
          "to": [
            800,
            960
          ],
          "stops": [
            {
              "offset": 0,
              "color": "#DEE8F1",
              "opacity": 0.5
            },
            {
              "offset": 0.24,
              "color": "#B9C7D7",
              "opacity": 0.08
            },
            {
              "offset": 0.72,
              "color": "#B9C7D7",
              "opacity": 0
            },
            {
              "offset": 1,
              "color": "#687786",
              "opacity": 0.14
            }
          ],
          "opacity": 0.12
        },
        "markGradient": {
          "kind": "linear",
          "from": [
            190.833333,
            345.485937
          ],
          "to": [
            872.333333,
            658.81927
          ],
          "stops": [
            {
              "offset": 0,
              "color": "#FFE7A6"
            },
            {
              "offset": 0.36,
              "color": "#F6C263"
            },
            {
              "offset": 0.72,
              "color": "#E9A04B"
            },
            {
              "offset": 1,
              "color": "#C9773C"
            }
          ]
        },
        "markLight": {
          "kind": "linear",
          "from": [
            120.333333,
            345.485937
          ],
          "to": [
            120.333333,
            705.81927
          ],
          "stops": [
            {
              "offset": 0,
              "color": "#FFFFFF",
              "opacity": 0.16
            },
            {
              "offset": 0.36,
              "color": "#FFFFFF",
              "opacity": 0.015
            },
            {
              "offset": 1,
              "color": "#FFFFFF",
              "opacity": 0
            }
          ]
        },
        "markRim": {
          "kind": "linear",
          "from": [
            198.666667,
            345.485937
          ],
          "to": [
            747,
            705.81927
          ],
          "stops": [
            {
              "offset": 0,
              "color": "#FFF6D2",
              "opacity": 0.7
            },
            {
              "offset": 0.5,
              "color": "#FFF2CD",
              "opacity": 0.2
            },
            {
              "offset": 1,
              "color": "#62330D",
              "opacity": 0.22
            }
          ]
        },
        "tileShadow0": {
          "kind": "solid",
          "color": "#060C15",
          "opacity": 0.014
        },
        "tileShadow1": {
          "kind": "solid",
          "color": "#060C15",
          "opacity": 0.02
        },
        "tileShadow2": {
          "kind": "solid",
          "color": "#060C15",
          "opacity": 0.028
        },
        "tileShadow3": {
          "kind": "solid",
          "color": "#060C15",
          "opacity": 0.038
        },
        "tileShadow4": {
          "kind": "solid",
          "color": "#060C15",
          "opacity": 0.07
        },
        "markShadow0": {
          "kind": "solid",
          "color": "#02050B",
          "opacity": 0.022
        },
        "markShadow1": {
          "kind": "solid",
          "color": "#02050B",
          "opacity": 0.032
        },
        "markShadow2": {
          "kind": "solid",
          "color": "#02050B",
          "opacity": 0.044
        },
        "markShadow3": {
          "kind": "solid",
          "color": "#02050B",
          "opacity": 0.064
        },
        "markShadow4": {
          "kind": "solid",
          "color": "#02050B",
          "opacity": 0.15
        }
      },
      "layers": [
        {
          "path": "tile",
          "paint": "tileShadow0",
          "mode": "fillStroke",
          "width": 40,
          "offset": [
            0,
            16
          ]
        },
        {
          "path": "tile",
          "paint": "tileShadow1",
          "mode": "fillStroke",
          "width": 30,
          "offset": [
            0,
            16
          ]
        },
        {
          "path": "tile",
          "paint": "tileShadow2",
          "mode": "fillStroke",
          "width": 20,
          "offset": [
            0,
            16
          ]
        },
        {
          "path": "tile",
          "paint": "tileShadow3",
          "mode": "fillStroke",
          "width": 10,
          "offset": [
            0,
            16
          ]
        },
        {
          "path": "tile",
          "paint": "tileShadow4",
          "mode": "fill",
          "offset": [
            0,
            16
          ]
        },
        {
          "path": "tile",
          "paint": "tileGradient",
          "mode": "fill"
        },
        {
          "path": "tile",
          "paint": "tileLight",
          "mode": "fill"
        },
        {
          "path": "tileSoftRim",
          "paint": "tileSoftRim",
          "mode": "stroke",
          "width": 9
        },
        {
          "path": "tileRim",
          "paint": "tileRim",
          "mode": "stroke",
          "width": 2.5
        },
        {
          "path": "mark",
          "paint": "markShadow0",
          "mode": "fillStroke",
          "width": 26,
          "offset": [
            0,
            8
          ]
        },
        {
          "path": "mark",
          "paint": "markShadow1",
          "mode": "fillStroke",
          "width": 19,
          "offset": [
            0,
            8
          ]
        },
        {
          "path": "mark",
          "paint": "markShadow2",
          "mode": "fillStroke",
          "width": 12,
          "offset": [
            0,
            8
          ]
        },
        {
          "path": "mark",
          "paint": "markShadow3",
          "mode": "fillStroke",
          "width": 6,
          "offset": [
            0,
            8
          ]
        },
        {
          "path": "mark",
          "paint": "markShadow4",
          "mode": "fill",
          "offset": [
            0,
            8
          ]
        },
        {
          "path": "mark",
          "paint": "markGradient",
          "mode": "fill"
        },
        {
          "path": "mark",
          "paint": "markLight",
          "mode": "fill"
        },
        {
          "path": "mark",
          "paint": "markRim",
          "mode": "stroke",
          "width": 1.4
        }
      ]
    }
    """#.utf8))

    static func drawAppIcon(in rect: CGRect, context: CGContext) throws {
        try BrandIconRenderer.draw(iconModel, in: rect, context: context)
    }
}
