// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
public import Foundation
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// - Remark: HTTP `GET /v1/button-destinations`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/get(getButtonDestinations)`.
    func getButtonDestinations(_ input: Operations.GetButtonDestinations.Input) async throws -> Operations.GetButtonDestinations.Output
    /// - Remark: HTTP `POST /v1/button-destinations`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/post(registerButtonDestination)`.
    func registerButtonDestination(_ input: Operations.RegisterButtonDestination.Input) async throws -> Operations.RegisterButtonDestination.Output
    /// - Remark: HTTP `POST /v1/button-destinations/{id}/heartbeat`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/heartbeat/post(heartbeatButtonDestination)`.
    func heartbeatButtonDestination(_ input: Operations.HeartbeatButtonDestination.Input) async throws -> Operations.HeartbeatButtonDestination.Output
    /// - Remark: HTTP `POST /v1/button-destinations/{id}/select`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/select/post(selectButtonDestination)`.
    func selectButtonDestination(_ input: Operations.SelectButtonDestination.Input) async throws -> Operations.SelectButtonDestination.Output
    /// - Remark: HTTP `POST /v1/button-destinations/{id}/complete`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/complete/post(completeButtonTake)`.
    func completeButtonTake(_ input: Operations.CompleteButtonTake.Input) async throws -> Operations.CompleteButtonTake.Output
    /// - Remark: HTTP `DELETE /v1/button-destinations/{id}`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/delete(unregisterButtonDestination)`.
    func unregisterButtonDestination(_ input: Operations.UnregisterButtonDestination.Input) async throws -> Operations.UnregisterButtonDestination.Output
    /// - Remark: HTTP `GET /v1/audio-sources`.
    /// - Remark: Generated from `#/paths//v1/audio-sources/get(listAudioSources)`.
    func listAudioSources(_ input: Operations.ListAudioSources.Input) async throws -> Operations.ListAudioSources.Output
    /// - Remark: HTTP `POST /v2/captures`.
    /// - Remark: Generated from `#/paths//v2/captures/post(startCapture)`.
    func startCapture(_ input: Operations.StartCapture.Input) async throws -> Operations.StartCapture.Output
    /// - Remark: HTTP `POST /v2/recordings/{id}/capture/heartbeat`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/capture/heartbeat/post(heartbeatCapture)`.
    func heartbeatCapture(_ input: Operations.HeartbeatCapture.Input) async throws -> Operations.HeartbeatCapture.Output
    /// - Remark: HTTP `POST /v2/recordings/{id}/capture/stop`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/capture/stop/post(stopCapture)`.
    func stopCapture(_ input: Operations.StopCapture.Input) async throws -> Operations.StopCapture.Output
    /// Fix a remote capture's continuation (or none) before its text processing starts.
    ///
    /// - Remark: HTTP `POST /v2/recordings/{id}/context`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/context/post(setCaptureContext)`.
    func setCaptureContext(_ input: Operations.SetCaptureContext.Input) async throws -> Operations.SetCaptureContext.Output
    /// - Remark: HTTP `GET /v2/recordings/{id}/events`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/events/get(recordingEvents)`.
    func recordingEvents(_ input: Operations.RecordingEvents.Input) async throws -> Operations.RecordingEvents.Output
    /// - Remark: HTTP `GET /v1/health`.
    /// - Remark: Generated from `#/paths//v1/health/get(getHealth)`.
    func getHealth(_ input: Operations.GetHealth.Input) async throws -> Operations.GetHealth.Output
    /// - Remark: HTTP `GET /v1/preferences`.
    /// - Remark: Generated from `#/paths//v1/preferences/get(getPreferences)`.
    func getPreferences(_ input: Operations.GetPreferences.Input) async throws -> Operations.GetPreferences.Output
    /// - Remark: HTTP `PUT /v1/preferences`.
    /// - Remark: Generated from `#/paths//v1/preferences/put(updatePreferences)`.
    func updatePreferences(_ input: Operations.UpdatePreferences.Input) async throws -> Operations.UpdatePreferences.Output
    /// - Remark: HTTP `GET /v1/generations`.
    /// - Remark: Generated from `#/paths//v1/generations/get(listGenerations)`.
    func listGenerations(_ input: Operations.ListGenerations.Input) async throws -> Operations.ListGenerations.Output
    /// - Remark: HTTP `POST /v1/generations`.
    /// - Remark: Generated from `#/paths//v1/generations/post(createGeneration)`.
    func createGeneration(_ input: Operations.CreateGeneration.Input) async throws -> Operations.CreateGeneration.Output
    /// - Remark: HTTP `GET /v1/generations/{id}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/get(getGeneration)`.
    func getGeneration(_ input: Operations.GetGeneration.Input) async throws -> Operations.GetGeneration.Output
    /// - Remark: HTTP `DELETE /v1/generations/{id}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/delete(deleteGeneration)`.
    func deleteGeneration(_ input: Operations.DeleteGeneration.Input) async throws -> Operations.DeleteGeneration.Output
    /// - Remark: HTTP `POST /v1/generations/{id}/audio/{kind}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/audio/{kind}/post(appendAudio)`.
    func appendAudio(_ input: Operations.AppendAudio.Input) async throws -> Operations.AppendAudio.Output
    /// - Remark: HTTP `POST /v1/generations/{id}/finish`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/finish/post(finishGeneration)`.
    func finishGeneration(_ input: Operations.FinishGeneration.Input) async throws -> Operations.FinishGeneration.Output
    /// - Remark: HTTP `POST /v1/generations/{id}/cancel`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/cancel/post(cancelGeneration)`.
    func cancelGeneration(_ input: Operations.CancelGeneration.Input) async throws -> Operations.CancelGeneration.Output
    /// - Remark: HTTP `POST /v1/generations/{id}/retry`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/retry/post(retryGeneration)`.
    func retryGeneration(_ input: Operations.RetryGeneration.Input) async throws -> Operations.RetryGeneration.Output
    /// - Remark: HTTP `POST /v1/generations/{id}/delivery`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/delivery/post(recordDelivery)`.
    func recordDelivery(_ input: Operations.RecordDelivery.Input) async throws -> Operations.RecordDelivery.Output
    /// A bounded NDJSON stream of complete GenerationRecord values, with the latest record repeated as a two-second heartbeat. Ends after a terminal record.
    ///
    /// - Remark: HTTP `GET /v1/generations/{id}/events`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/events/get(generationEvents)`.
    func generationEvents(_ input: Operations.GenerationEvents.Input) async throws -> Operations.GenerationEvents.Output
    /// - Remark: HTTP `GET /v1/generations/{id}/artifacts/{filename}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/artifacts/{filename}/get(downloadArtifact)`.
    func downloadArtifact(_ input: Operations.DownloadArtifact.Input) async throws -> Operations.DownloadArtifact.Output
    /// - Remark: HTTP `POST /v1/imports/wispr-flow/known`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/known/post(knownWisprFlowIDs)`.
    func knownWisprFlowIDs(_ input: Operations.KnownWisprFlowIDs.Input) async throws -> Operations.KnownWisprFlowIDs.Output
    /// - Remark: HTTP `POST /v1/imports/wispr-flow`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/post(beginWisprFlowImport)`.
    func beginWisprFlowImport(_ input: Operations.BeginWisprFlowImport.Input) async throws -> Operations.BeginWisprFlowImport.Output
    /// - Remark: HTTP `PUT /v1/imports/wispr-flow/dictionary`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/dictionary/put(archiveWisprFlowDictionary)`.
    func archiveWisprFlowDictionary(_ input: Operations.ArchiveWisprFlowDictionary.Input) async throws -> Operations.ArchiveWisprFlowDictionary.Output
    /// - Remark: HTTP `PUT /v1/imports/wispr-flow/{id}/artifacts/{filename}`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/{id}/artifacts/{filename}/put(uploadWisprFlowArtifact)`.
    func uploadWisprFlowArtifact(_ input: Operations.UploadWisprFlowArtifact.Input) async throws -> Operations.UploadWisprFlowArtifact.Output
    /// - Remark: HTTP `POST /v1/imports/wispr-flow/{id}/complete`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/{id}/complete/post(completeWisprFlowImport)`.
    func completeWisprFlowImport(_ input: Operations.CompleteWisprFlowImport.Input) async throws -> Operations.CompleteWisprFlowImport.Output
    /// - Remark: HTTP `DELETE /v1/imports/wispr-flow/{id}`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/{id}/delete(cancelWisprFlowImport)`.
    func cancelWisprFlowImport(_ input: Operations.CancelWisprFlowImport.Input) async throws -> Operations.CancelWisprFlowImport.Output
    /// - Remark: HTTP `GET /v2/recordings/capabilities`.
    /// - Remark: Generated from `#/paths//v2/recordings/capabilities/get(getRecordingCapabilities)`.
    func getRecordingCapabilities(_ input: Operations.GetRecordingCapabilities.Input) async throws -> Operations.GetRecordingCapabilities.Output
    /// - Remark: HTTP `GET /v2/recordings`.
    /// - Remark: Generated from `#/paths//v2/recordings/get(listRecordings)`.
    func listRecordings(_ input: Operations.ListRecordings.Input) async throws -> Operations.ListRecordings.Output
    /// - Remark: HTTP `POST /v2/recordings`.
    /// - Remark: Generated from `#/paths//v2/recordings/post(createRecording)`.
    func createRecording(_ input: Operations.CreateRecording.Input) async throws -> Operations.CreateRecording.Output
    /// - Remark: HTTP `GET /v2/recordings/{id}`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/get(getRecording)`.
    func getRecording(_ input: Operations.GetRecording.Input) async throws -> Operations.GetRecording.Output
    /// - Remark: HTTP `GET /v2/recordings/{id}/transcript`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/transcript/get(getRecordingTranscript)`.
    func getRecordingTranscript(_ input: Operations.GetRecordingTranscript.Input) async throws -> Operations.GetRecordingTranscript.Output
    /// - Remark: HTTP `GET /v2/recordings/{id}/audio/{kind}`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/audio/{kind}/get(getRecordingAudio)`.
    func getRecordingAudio(_ input: Operations.GetRecordingAudio.Input) async throws -> Operations.GetRecordingAudio.Output
    /// - Remark: HTTP `POST /v2/recordings/{id}/discard`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/discard/post(discardRecording)`.
    func discardRecording(_ input: Operations.DiscardRecording.Input) async throws -> Operations.DiscardRecording.Output
    /// Resume a failed recording's processing from its committed text with local recognition. Nothing is delivered.
    ///
    /// - Remark: HTTP `POST /v2/recordings/{id}/retry`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/retry/post(retryRecording)`.
    func retryRecording(_ input: Operations.RetryRecording.Input) async throws -> Operations.RetryRecording.Output
    /// - Remark: HTTP `POST /v2/recordings/{id}/delivery`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/delivery/post(recordRecordingDelivery)`.
    func recordRecordingDelivery(_ input: Operations.RecordRecordingDelivery.Input) async throws -> Operations.RecordRecordingDelivery.Output
    /// Upgrade to WebSocket subprotocol sottoduo.recording.v1. Binary audio is UInt32BE JSON header length, UTF8 RecordingAudioHeader, then little-endian float32 PCM. Text controls resume, context, pause, stop and ping; server sends snapshots, acknowledgments, progress and errors. See docs/recording-protocol.md for durable ACK, fencing and resume semantics.
    ///
    /// - Remark: HTTP `GET /v2/recordings/{id}/stream`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/stream/get(streamRecording)`.
    func streamRecording(_ input: Operations.StreamRecording.Input) async throws -> Operations.StreamRecording.Output
    /// - Remark: HTTP `GET /v2/recordings/{id}/audio/{kind}/{runID}`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/audio/{kind}/{runID}/get(getRecordingRunAudio)`.
    func getRecordingRunAudio(_ input: Operations.GetRecordingRunAudio.Input) async throws -> Operations.GetRecordingRunAudio.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `GET /v1/button-destinations`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/get(getButtonDestinations)`.
    public func getButtonDestinations(headers: Operations.GetButtonDestinations.Input.Headers = .init()) async throws -> Operations.GetButtonDestinations.Output {
        try await getButtonDestinations(Operations.GetButtonDestinations.Input(headers: headers))
    }
    /// - Remark: HTTP `POST /v1/button-destinations`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/post(registerButtonDestination)`.
    public func registerButtonDestination(
        headers: Operations.RegisterButtonDestination.Input.Headers,
        body: Operations.RegisterButtonDestination.Input.Body
    ) async throws -> Operations.RegisterButtonDestination.Output {
        try await registerButtonDestination(Operations.RegisterButtonDestination.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/button-destinations/{id}/heartbeat`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/heartbeat/post(heartbeatButtonDestination)`.
    public func heartbeatButtonDestination(
        path: Operations.HeartbeatButtonDestination.Input.Path,
        headers: Operations.HeartbeatButtonDestination.Input.Headers,
        body: Operations.HeartbeatButtonDestination.Input.Body
    ) async throws -> Operations.HeartbeatButtonDestination.Output {
        try await heartbeatButtonDestination(Operations.HeartbeatButtonDestination.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/button-destinations/{id}/select`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/select/post(selectButtonDestination)`.
    public func selectButtonDestination(
        path: Operations.SelectButtonDestination.Input.Path,
        headers: Operations.SelectButtonDestination.Input.Headers,
        body: Operations.SelectButtonDestination.Input.Body
    ) async throws -> Operations.SelectButtonDestination.Output {
        try await selectButtonDestination(Operations.SelectButtonDestination.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/button-destinations/{id}/complete`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/complete/post(completeButtonTake)`.
    public func completeButtonTake(
        path: Operations.CompleteButtonTake.Input.Path,
        headers: Operations.CompleteButtonTake.Input.Headers,
        body: Operations.CompleteButtonTake.Input.Body
    ) async throws -> Operations.CompleteButtonTake.Output {
        try await completeButtonTake(Operations.CompleteButtonTake.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `DELETE /v1/button-destinations/{id}`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/delete(unregisterButtonDestination)`.
    public func unregisterButtonDestination(
        path: Operations.UnregisterButtonDestination.Input.Path,
        headers: Operations.UnregisterButtonDestination.Input.Headers
    ) async throws -> Operations.UnregisterButtonDestination.Output {
        try await unregisterButtonDestination(Operations.UnregisterButtonDestination.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v1/audio-sources`.
    /// - Remark: Generated from `#/paths//v1/audio-sources/get(listAudioSources)`.
    public func listAudioSources(headers: Operations.ListAudioSources.Input.Headers = .init()) async throws -> Operations.ListAudioSources.Output {
        try await listAudioSources(Operations.ListAudioSources.Input(headers: headers))
    }
    /// - Remark: HTTP `POST /v2/captures`.
    /// - Remark: Generated from `#/paths//v2/captures/post(startCapture)`.
    public func startCapture(
        headers: Operations.StartCapture.Input.Headers,
        body: Operations.StartCapture.Input.Body
    ) async throws -> Operations.StartCapture.Output {
        try await startCapture(Operations.StartCapture.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v2/recordings/{id}/capture/heartbeat`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/capture/heartbeat/post(heartbeatCapture)`.
    public func heartbeatCapture(
        path: Operations.HeartbeatCapture.Input.Path,
        headers: Operations.HeartbeatCapture.Input.Headers
    ) async throws -> Operations.HeartbeatCapture.Output {
        try await heartbeatCapture(Operations.HeartbeatCapture.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v2/recordings/{id}/capture/stop`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/capture/stop/post(stopCapture)`.
    public func stopCapture(
        path: Operations.StopCapture.Input.Path,
        headers: Operations.StopCapture.Input.Headers,
        body: Operations.StopCapture.Input.Body
    ) async throws -> Operations.StopCapture.Output {
        try await stopCapture(Operations.StopCapture.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Fix a remote capture's continuation (or none) before its text processing starts.
    ///
    /// - Remark: HTTP `POST /v2/recordings/{id}/context`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/context/post(setCaptureContext)`.
    public func setCaptureContext(
        path: Operations.SetCaptureContext.Input.Path,
        headers: Operations.SetCaptureContext.Input.Headers,
        body: Operations.SetCaptureContext.Input.Body
    ) async throws -> Operations.SetCaptureContext.Output {
        try await setCaptureContext(Operations.SetCaptureContext.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /v2/recordings/{id}/events`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/events/get(recordingEvents)`.
    public func recordingEvents(
        path: Operations.RecordingEvents.Input.Path,
        headers: Operations.RecordingEvents.Input.Headers = .init()
    ) async throws -> Operations.RecordingEvents.Output {
        try await recordingEvents(Operations.RecordingEvents.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v1/health`.
    /// - Remark: Generated from `#/paths//v1/health/get(getHealth)`.
    public func getHealth(headers: Operations.GetHealth.Input.Headers = .init()) async throws -> Operations.GetHealth.Output {
        try await getHealth(Operations.GetHealth.Input(headers: headers))
    }
    /// - Remark: HTTP `GET /v1/preferences`.
    /// - Remark: Generated from `#/paths//v1/preferences/get(getPreferences)`.
    public func getPreferences(headers: Operations.GetPreferences.Input.Headers = .init()) async throws -> Operations.GetPreferences.Output {
        try await getPreferences(Operations.GetPreferences.Input(headers: headers))
    }
    /// - Remark: HTTP `PUT /v1/preferences`.
    /// - Remark: Generated from `#/paths//v1/preferences/put(updatePreferences)`.
    public func updatePreferences(
        headers: Operations.UpdatePreferences.Input.Headers = .init(),
        body: Operations.UpdatePreferences.Input.Body
    ) async throws -> Operations.UpdatePreferences.Output {
        try await updatePreferences(Operations.UpdatePreferences.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /v1/generations`.
    /// - Remark: Generated from `#/paths//v1/generations/get(listGenerations)`.
    public func listGenerations(
        query: Operations.ListGenerations.Input.Query = .init(),
        headers: Operations.ListGenerations.Input.Headers = .init()
    ) async throws -> Operations.ListGenerations.Output {
        try await listGenerations(Operations.ListGenerations.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/generations`.
    /// - Remark: Generated from `#/paths//v1/generations/post(createGeneration)`.
    public func createGeneration(
        headers: Operations.CreateGeneration.Input.Headers = .init(),
        body: Operations.CreateGeneration.Input.Body
    ) async throws -> Operations.CreateGeneration.Output {
        try await createGeneration(Operations.CreateGeneration.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /v1/generations/{id}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/get(getGeneration)`.
    public func getGeneration(
        path: Operations.GetGeneration.Input.Path,
        headers: Operations.GetGeneration.Input.Headers = .init()
    ) async throws -> Operations.GetGeneration.Output {
        try await getGeneration(Operations.GetGeneration.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `DELETE /v1/generations/{id}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/delete(deleteGeneration)`.
    public func deleteGeneration(
        path: Operations.DeleteGeneration.Input.Path,
        headers: Operations.DeleteGeneration.Input.Headers = .init()
    ) async throws -> Operations.DeleteGeneration.Output {
        try await deleteGeneration(Operations.DeleteGeneration.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/generations/{id}/audio/{kind}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/audio/{kind}/post(appendAudio)`.
    public func appendAudio(
        path: Operations.AppendAudio.Input.Path,
        query: Operations.AppendAudio.Input.Query,
        headers: Operations.AppendAudio.Input.Headers = .init(),
        body: Operations.AppendAudio.Input.Body
    ) async throws -> Operations.AppendAudio.Output {
        try await appendAudio(Operations.AppendAudio.Input(
            path: path,
            query: query,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/generations/{id}/finish`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/finish/post(finishGeneration)`.
    public func finishGeneration(
        path: Operations.FinishGeneration.Input.Path,
        headers: Operations.FinishGeneration.Input.Headers = .init(),
        body: Operations.FinishGeneration.Input.Body
    ) async throws -> Operations.FinishGeneration.Output {
        try await finishGeneration(Operations.FinishGeneration.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/generations/{id}/cancel`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/cancel/post(cancelGeneration)`.
    public func cancelGeneration(
        path: Operations.CancelGeneration.Input.Path,
        headers: Operations.CancelGeneration.Input.Headers = .init()
    ) async throws -> Operations.CancelGeneration.Output {
        try await cancelGeneration(Operations.CancelGeneration.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/generations/{id}/retry`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/retry/post(retryGeneration)`.
    public func retryGeneration(
        path: Operations.RetryGeneration.Input.Path,
        headers: Operations.RetryGeneration.Input.Headers = .init()
    ) async throws -> Operations.RetryGeneration.Output {
        try await retryGeneration(Operations.RetryGeneration.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/generations/{id}/delivery`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/delivery/post(recordDelivery)`.
    public func recordDelivery(
        path: Operations.RecordDelivery.Input.Path,
        headers: Operations.RecordDelivery.Input.Headers = .init(),
        body: Operations.RecordDelivery.Input.Body
    ) async throws -> Operations.RecordDelivery.Output {
        try await recordDelivery(Operations.RecordDelivery.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// A bounded NDJSON stream of complete GenerationRecord values, with the latest record repeated as a two-second heartbeat. Ends after a terminal record.
    ///
    /// - Remark: HTTP `GET /v1/generations/{id}/events`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/events/get(generationEvents)`.
    public func generationEvents(
        path: Operations.GenerationEvents.Input.Path,
        headers: Operations.GenerationEvents.Input.Headers = .init()
    ) async throws -> Operations.GenerationEvents.Output {
        try await generationEvents(Operations.GenerationEvents.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v1/generations/{id}/artifacts/{filename}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/artifacts/{filename}/get(downloadArtifact)`.
    public func downloadArtifact(
        path: Operations.DownloadArtifact.Input.Path,
        headers: Operations.DownloadArtifact.Input.Headers = .init()
    ) async throws -> Operations.DownloadArtifact.Output {
        try await downloadArtifact(Operations.DownloadArtifact.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/imports/wispr-flow/known`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/known/post(knownWisprFlowIDs)`.
    public func knownWisprFlowIDs(
        headers: Operations.KnownWisprFlowIDs.Input.Headers = .init(),
        body: Operations.KnownWisprFlowIDs.Input.Body
    ) async throws -> Operations.KnownWisprFlowIDs.Output {
        try await knownWisprFlowIDs(Operations.KnownWisprFlowIDs.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/imports/wispr-flow`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/post(beginWisprFlowImport)`.
    public func beginWisprFlowImport(
        headers: Operations.BeginWisprFlowImport.Input.Headers = .init(),
        body: Operations.BeginWisprFlowImport.Input.Body
    ) async throws -> Operations.BeginWisprFlowImport.Output {
        try await beginWisprFlowImport(Operations.BeginWisprFlowImport.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `PUT /v1/imports/wispr-flow/dictionary`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/dictionary/put(archiveWisprFlowDictionary)`.
    public func archiveWisprFlowDictionary(
        headers: Operations.ArchiveWisprFlowDictionary.Input.Headers = .init(),
        body: Operations.ArchiveWisprFlowDictionary.Input.Body
    ) async throws -> Operations.ArchiveWisprFlowDictionary.Output {
        try await archiveWisprFlowDictionary(Operations.ArchiveWisprFlowDictionary.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `PUT /v1/imports/wispr-flow/{id}/artifacts/{filename}`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/{id}/artifacts/{filename}/put(uploadWisprFlowArtifact)`.
    public func uploadWisprFlowArtifact(
        path: Operations.UploadWisprFlowArtifact.Input.Path,
        headers: Operations.UploadWisprFlowArtifact.Input.Headers = .init(),
        body: Operations.UploadWisprFlowArtifact.Input.Body
    ) async throws -> Operations.UploadWisprFlowArtifact.Output {
        try await uploadWisprFlowArtifact(Operations.UploadWisprFlowArtifact.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/imports/wispr-flow/{id}/complete`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/{id}/complete/post(completeWisprFlowImport)`.
    public func completeWisprFlowImport(
        path: Operations.CompleteWisprFlowImport.Input.Path,
        headers: Operations.CompleteWisprFlowImport.Input.Headers = .init()
    ) async throws -> Operations.CompleteWisprFlowImport.Output {
        try await completeWisprFlowImport(Operations.CompleteWisprFlowImport.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `DELETE /v1/imports/wispr-flow/{id}`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/{id}/delete(cancelWisprFlowImport)`.
    public func cancelWisprFlowImport(
        path: Operations.CancelWisprFlowImport.Input.Path,
        headers: Operations.CancelWisprFlowImport.Input.Headers = .init()
    ) async throws -> Operations.CancelWisprFlowImport.Output {
        try await cancelWisprFlowImport(Operations.CancelWisprFlowImport.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v2/recordings/capabilities`.
    /// - Remark: Generated from `#/paths//v2/recordings/capabilities/get(getRecordingCapabilities)`.
    public func getRecordingCapabilities(headers: Operations.GetRecordingCapabilities.Input.Headers = .init()) async throws -> Operations.GetRecordingCapabilities.Output {
        try await getRecordingCapabilities(Operations.GetRecordingCapabilities.Input(headers: headers))
    }
    /// - Remark: HTTP `GET /v2/recordings`.
    /// - Remark: Generated from `#/paths//v2/recordings/get(listRecordings)`.
    public func listRecordings(
        query: Operations.ListRecordings.Input.Query = .init(),
        headers: Operations.ListRecordings.Input.Headers = .init()
    ) async throws -> Operations.ListRecordings.Output {
        try await listRecordings(Operations.ListRecordings.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v2/recordings`.
    /// - Remark: Generated from `#/paths//v2/recordings/post(createRecording)`.
    public func createRecording(
        headers: Operations.CreateRecording.Input.Headers = .init(),
        body: Operations.CreateRecording.Input.Body
    ) async throws -> Operations.CreateRecording.Output {
        try await createRecording(Operations.CreateRecording.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /v2/recordings/{id}`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/get(getRecording)`.
    public func getRecording(
        path: Operations.GetRecording.Input.Path,
        headers: Operations.GetRecording.Input.Headers = .init()
    ) async throws -> Operations.GetRecording.Output {
        try await getRecording(Operations.GetRecording.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v2/recordings/{id}/transcript`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/transcript/get(getRecordingTranscript)`.
    public func getRecordingTranscript(
        path: Operations.GetRecordingTranscript.Input.Path,
        headers: Operations.GetRecordingTranscript.Input.Headers = .init()
    ) async throws -> Operations.GetRecordingTranscript.Output {
        try await getRecordingTranscript(Operations.GetRecordingTranscript.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v2/recordings/{id}/audio/{kind}`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/audio/{kind}/get(getRecordingAudio)`.
    public func getRecordingAudio(
        path: Operations.GetRecordingAudio.Input.Path,
        headers: Operations.GetRecordingAudio.Input.Headers = .init()
    ) async throws -> Operations.GetRecordingAudio.Output {
        try await getRecordingAudio(Operations.GetRecordingAudio.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v2/recordings/{id}/discard`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/discard/post(discardRecording)`.
    public func discardRecording(
        path: Operations.DiscardRecording.Input.Path,
        headers: Operations.DiscardRecording.Input.Headers = .init()
    ) async throws -> Operations.DiscardRecording.Output {
        try await discardRecording(Operations.DiscardRecording.Input(
            path: path,
            headers: headers
        ))
    }
    /// Resume a failed recording's processing from its committed text with local recognition. Nothing is delivered.
    ///
    /// - Remark: HTTP `POST /v2/recordings/{id}/retry`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/retry/post(retryRecording)`.
    public func retryRecording(
        path: Operations.RetryRecording.Input.Path,
        headers: Operations.RetryRecording.Input.Headers = .init()
    ) async throws -> Operations.RetryRecording.Output {
        try await retryRecording(Operations.RetryRecording.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v2/recordings/{id}/delivery`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/delivery/post(recordRecordingDelivery)`.
    public func recordRecordingDelivery(
        path: Operations.RecordRecordingDelivery.Input.Path,
        headers: Operations.RecordRecordingDelivery.Input.Headers = .init(),
        body: Operations.RecordRecordingDelivery.Input.Body
    ) async throws -> Operations.RecordRecordingDelivery.Output {
        try await recordRecordingDelivery(Operations.RecordRecordingDelivery.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Upgrade to WebSocket subprotocol sottoduo.recording.v1. Binary audio is UInt32BE JSON header length, UTF8 RecordingAudioHeader, then little-endian float32 PCM. Text controls resume, context, pause, stop and ping; server sends snapshots, acknowledgments, progress and errors. See docs/recording-protocol.md for durable ACK, fencing and resume semantics.
    ///
    /// - Remark: HTTP `GET /v2/recordings/{id}/stream`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/stream/get(streamRecording)`.
    public func streamRecording(
        path: Operations.StreamRecording.Input.Path,
        headers: Operations.StreamRecording.Input.Headers = .init()
    ) async throws -> Operations.StreamRecording.Output {
        try await streamRecording(Operations.StreamRecording.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v2/recordings/{id}/audio/{kind}/{runID}`.
    /// - Remark: Generated from `#/paths//v2/recordings/{id}/audio/{kind}/{runID}/get(getRecordingRunAudio)`.
    public func getRecordingRunAudio(
        path: Operations.GetRecordingRunAudio.Input.Path,
        headers: Operations.GetRecordingRunAudio.Input.Headers = .init()
    ) async throws -> Operations.GetRecordingRunAudio.Output {
        try await getRecordingRunAudio(Operations.GetRecordingRunAudio.Input(
            path: path,
            headers: headers
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    public enum Server1 {
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "http://localhost:8391",
                variables: []
            )
        }
    }
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "http://localhost:8391",
            variables: []
        )
    }
}
